services:
  wol-remote:
    image: "wol-remote:latest"
    ports:
      - "6020:8090"
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
    network_mode: host # Critical: enables proper UDP broadcast on Linux